Madhuri
Haseeb08/Rehabit pull request #7
Opened 2020-04-22 07:36 UTC by Madhuri1518

2020-04-22 08:02 UTC, ghost approved these changes

2020-04-23 11:24 UTC, MallipeddiRuchitha reviewed
why did you use seperate configuration class to create authservice bean.

2020-04-23 13:43 UTC, sahithm06 requested changes
properties  must be stored in .env  file and  add it to .gitignore

2020-04-23 13:53 UTC, MallipeddiRuchitha requested changes
Retrieve twilio properties from .env file

2020-04-30 12:05 UTC, merged